In [3]:
import numpy as np

In [5]:
a = np.array([5,5,5])

In [6]:
a

array([5, 5, 5])

In [7]:
type(a)

numpy.ndarray

In [8]:
b= np.array([[5,5,5],[5,5,5],[5,5,5]])

In [9]:
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [10]:
len(b)

3

In [11]:
b[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
b[1:]

array([[5, 5, 5],
       [5, 5, 5]])

In [14]:
b[2:]

array([[5, 5, 5]])

In [15]:
a[0:]

array([5, 5, 5])

In [16]:
a[1:]

array([5, 5])

In [17]:
a[2:]

array([5])

In [18]:
a[3:]

array([], dtype=int32)

## 1D Array

In [19]:
c =np.array([1,2,3,4,5])

In [20]:
c

array([1, 2, 3, 4, 5])

In [21]:
d= np.zeros(2)

In [22]:
d

array([0., 0.])

In [24]:
e=np.ones(3)

In [25]:
e

array([1., 1., 1.])

In [26]:
f = np.empty(3)

In [27]:
f

array([1., 1., 1.])

In [28]:
g=np.arange(6)

In [29]:
g

array([0, 1, 2, 3, 4, 5])

In [30]:
h=np.arange(2,20)

In [31]:
h

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [32]:
i =np.arange(2,20,2)

In [33]:
i

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
j =np.linspace(0,10,num=5)

In [36]:
j

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
k = np.ones(5, dtype=np.int8)

In [39]:
k

array([1, 1, 1, 1, 1], dtype=int8)

In [43]:
l =np.ones(3, dtype=np.float64)

In [44]:
l

array([1., 1., 1.])

## 2D Array

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [48]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
# making and reshaping a 3D array
m =np.arange(24).reshape(2,3,4)

In [50]:
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])