# numpy practice session

In [1]:
#pip install numpy

In [1]:
import numpy as np

# Creating an array using numpy

In [2]:
food=np.array(["pakoar","samosa","Raita"])
food

array(['pakoar', 'samosa', 'Raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [8]:
price[2]

5

In [9]:
price[0:]

array([5, 5, 5])

In [10]:
food[1]

'samosa'

In [11]:
price.mean()

5.0

In [12]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
#line space
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [25]:
# specify your data type
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [26]:
# specify your data type
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Functions

In [29]:
a= np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [31]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [32]:
b = np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [33]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [35]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D Array

In [42]:
a = np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [43]:
b=np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [44]:
np.concatenate((a,b))

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [45]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [46]:
np.concatenate((a,b),axis=1)

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [50]:
a=np.array([[[1,2,3],[4,5,6]],
          [[7,8,9],[10,11,12]],
          [[13,14,15],[16,17,18]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [53]:
#to find the number of dimensions
a.ndim

3

In [54]:
b=np.array([[21,22,23],
           [24,25,26],
           [27,28,29]])
b

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [55]:
b.ndim

2

In [56]:
a.size

18

In [57]:
#shape
a.shape

(3, 2, 3)

In [60]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [63]:
#reshape
a = a.reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [68]:
#reshape
a = a.reshape(3,2)
a


array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
#reshape
np.reshape(a,newshape=(1,6),order='C')

array([[0, 1, 2, 3, 4, 5]])

In [74]:
# convert 1D to 2D
a =  np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a.shape

(9,)

In [77]:
#rowwise 2D
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [78]:
b.shape

(1, 9)

In [79]:
#columwise 2D
c = a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [80]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a[2:6]

array([3, 4, 5, 6])

In [82]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [83]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [84]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
a.sum()

45

In [86]:
a.mean()

5.0